<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="minibot_light_01">
  <!-- https://en.wikipedia.org/wiki/List_of_moments_of_inertia -->
  <xacro:macro name="cylinder_inertia" params="m r h">
    <mass value="${m}"/>
    <inertia ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0" iyy="${m*(3*r*r+h*h)/12}" iyz = "0" izz="${m*r*r/2}" />
  </xacro:macro>
  <xacro:macro name="box_inertia" params="m x y z">
    <mass value="${m}"/>
    <inertia ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0" iyy="${m*(x*x+z*z)/12}" iyz = "0" izz="${m*(x*x+z*z)/12}" />
  </xacro:macro>
  <xacro:macro name="sphere_inertia" params="m r">
    <mass value="${m}"/>
    <inertia ixx="${2*m*r*r/5}" ixy = "0" ixz = "0" iyy="${2*m*r*r/5}" iyz = "0" izz="${2*m*r*r/5}" />
  </xacro:macro>

  <material name="vehicle_mat">
    <color rgba="1.0 0.0 0.0 0.5"/>
  </material>

  <material name="laser_mat">
    <color rgba="0.0 0.0 1.0 0.8"/>
  </material>

  <link name="base_link"/>

  <xacro:property name="body_space" value="0.0195" />
  <xacro:property name="body_size_x" value="0.23" />
  <xacro:property name="body_size_y" value="0.23" />
  <xacro:property name="body_collision_y" value="0.15" />
  <xacro:property name="body_size_z" value="${0.132 - body_space}" />
  <!-- 0.1125 -->
  <xacro:property name="body_x" value="-0.05" />
  <xacro:property name="body_z" value="${body_space + body_size_z/2}" />
  <!-- 0.07575 -->
  <xacro:property name="body_mass" value="1.0" />
  <xacro:property name="body_panel_thickness" value="0.0055" />
  <xacro:property name="body_panel_1_z" value="${-body_size_z/2 + body_panel_thickness/2}" />
  <xacro:property name="body_panel_2_z" value="${body_panel_1_z + 0.05050}" />
  <xacro:property name="body_panel_3_z" value="${body_panel_2_z + 0.05650}" />

  <joint name="body_joint" type="fixed">
    <origin rpy="0 0 0" xyz="${body_x} 0 ${body_z}"/>
    <parent link="base_link"/>
    <child link="body_link"/>
  </joint>

  <link name="body_link">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="${body_size_x} ${body_collision_y} ${body_size_z}"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 ${body_panel_1_z}"/>
      <geometry>
        <box size="${body_size_x} ${body_size_y} ${body_panel_thickness}"/>
      </geometry>
      <material name="vehicle_mat"/>
    </visual>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 ${body_panel_2_z}"/>
      <geometry>
        <box size="${body_size_x} ${body_size_y} ${body_panel_thickness}"/>
      </geometry>
      <material name="vehicle_mat"/>
    </visual>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 ${body_panel_3_z}"/>
      <geometry>
        <box size="${body_size_x} ${body_size_y} ${body_panel_thickness}"/>
      </geometry>
      <material name="vehicle_mat"/>
    </visual>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <xacro:box_inertia m="${body_mass}" x="${body_size_x}" y="${body_collision_y}" z="${body_size_z}"/>
    </inertial>
  </link>

  <gazebo reference="body_link">
    <material>Gazebo/Red</material>
    <mu1>0.05</mu1>
    <mu2>0.05</mu2>
  </gazebo>

  <xacro:property name="laser_radius" value="0.0328" />
  <xacro:property name="laser_size_z" value="0.0352" />
  <xacro:property name="laser_x" value="0.03" />
  <xacro:property name="laser_z" value="${0.025 + laser_size_z/2}" />
  <xacro:property name="laser_mass" value="0.180" />

  <joint name="laser_joint" type="fixed">
    <origin xyz="${laser_x} 0 ${laser_z}" rpy="0 0 ${radians(-90)}"/>
    <parent link="base_link"/>
    <child link="base_laser_link"/>
  </joint>

  <link name="base_laser_link">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder radius="${laser_radius}" length="${laser_size_z}"/>
      </geometry>
    </collision>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder radius="${laser_radius}" length="${laser_size_z}"/>
      </geometry>
      <material name="laser_mat"/>
    </visual>
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <xacro:cylinder_inertia m="${laser_mass}" r="${laser_radius}" h="${laser_size_z}"/>
    </inertial>
  </link>

  <gazebo reference="base_laser_link">
    <material>Gazebo/Blue</material>
    <mu1>0.05</mu1>
    <mu2>0.05</mu2>
  </gazebo>
</robot>
